// Code generated by protoc-gen-go. DO NOT EDIT.
// source: probeserver/probeserver.proto

package probeserver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/google/cloudprober/probes/external/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProbeClient is the client API for Probe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProbeClient interface {
	Serve(ctx context.Context, in *proto1.ProbeRequest, opts ...grpc.CallOption) (*proto1.ProbeReply, error)
}

type probeClient struct {
	cc *grpc.ClientConn
}

func NewProbeClient(cc *grpc.ClientConn) ProbeClient {
	return &probeClient{cc}
}

func (c *probeClient) Serve(ctx context.Context, in *proto1.ProbeRequest, opts ...grpc.CallOption) (*proto1.ProbeReply, error) {
	out := new(proto1.ProbeReply)
	err := c.cc.Invoke(ctx, "/probeserver.Probe/Serve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProbeServer is the server API for Probe service.
type ProbeServer interface {
	Serve(context.Context, *proto1.ProbeRequest) (*proto1.ProbeReply, error)
}

func RegisterProbeServer(s *grpc.Server, srv ProbeServer) {
	s.RegisterService(&_Probe_serviceDesc, srv)
}

func _Probe_Serve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.ProbeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProbeServer).Serve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/probeserver.Probe/Serve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProbeServer).Serve(ctx, req.(*proto1.ProbeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Probe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "probeserver.Probe",
	HandlerType: (*ProbeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Serve",
			Handler:    _Probe_Serve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "probeserver/probeserver.proto",
}

func init() {
	proto.RegisterFile("probeserver/probeserver.proto", fileDescriptor_probeserver_413f81e6e0fa699f)
}

var fileDescriptor_probeserver_413f81e6e0fa699f = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x4f,
	0x4a, 0x2d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x47, 0x62, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4,
	0x0b, 0x71, 0x23, 0x09, 0x49, 0x39, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0xa7, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0xe7, 0xe4, 0x97, 0xa6, 0x80, 0xd5, 0xc0,
	0x74, 0xeb, 0xa7, 0x56, 0x94, 0xa4, 0x16, 0xe5, 0x25, 0xe6, 0xe8, 0x83, 0x4d, 0xd0, 0x47, 0x36,
	0xce, 0xc8, 0x8d, 0x8b, 0x35, 0x00, 0xa4, 0x4a, 0xc8, 0x96, 0x8b, 0x35, 0x18, 0x24, 0x21, 0x24,
	0xa9, 0x87, 0x64, 0x84, 0x1e, 0x58, 0x32, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x4a, 0x1c,
	0x9b, 0x54, 0x41, 0x4e, 0xa5, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x38, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0x0f, 0xc0, 0x40, 0xbe, 0x00, 0x00, 0x00,
}
